name: "Release echo docker"

# @see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    tags:
      - v1*

jobs:
  docker:
    name: releases-by-docker
    runs-on: ubuntu-20.04

    steps:
      ################################################################
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      ################################################################
      # Build
      # The github.ref is, for example, refs/tags/v1.0.52
      # Generate variables like:
      #   SRS_TAG=releases-v1.0.52
      #   SRS_MAJOR=releases-1
      # @see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Generate varaiables
        run: |
          SRS_TAG=$(echo ${{ github.ref }}| awk -F '/' '{print $3}')
          echo "SRS_TAG=$SRS_TAG" >> $GITHUB_ENV
          SRS_MAJOR=$(echo $SRS_TAG| awk -F '.' '{print $1}' |sed 's/-v/-/g')
          echo "SRS_MAJOR=$SRS_MAJOR" >> $GITHUB_ENV
      # Build SRS image
      - name: Build SRS docker image
        run: |
          echo "Release ossrs/echo:$SRS_TAG"
          docker build --tag ossrs/echo:$SRS_TAG -f releases/Dockerfile .

      ################################################################
      # Docker hub for global user
      - name: Login docker hub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Push to docker hub
        run: |
          docker tag ossrs/echo:$SRS_TAG ossrs/echo:$SRS_TAG
          docker tag ossrs/echo:$SRS_TAG ossrs/echo:$SRS_MAJOR
          docker push --all-tags ossrs/echo
          echo "Release ok, please see:"
          echo "  https://hub.docker.com/r/ossrs/echo/tags"

      ################################################################
      # Aliyun ACR
      - name: Login Aliyun docker hub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Push to Aliyun docker hub
        run: |
          docker tag ossrs/echo:$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/echo:$SRS_TAG
          docker tag ossrs/echo:$SRS_TAG registry.cn-hangzhou.aliyuncs.com/ossrs/echo:$SRS_MAJOR
          docker push --all-tags registry.cn-hangzhou.aliyuncs.com/ossrs/echo
          echo "Release ok, please see:"
          echo "  https://cr.console.aliyun.com/repository/cn-hangzhou/ossrs/echo/images"
